RC/SmartTrip/src/SmartTrip/Models/Trip.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SmartTrip.Models
{
    public class Trip
    {
        public Trip() {

            StartTime = new DateTime();

        }
       

        public int Id { get; set; }

        public string TripName { get; set; }
 
        [ScaffoldColumn(false)]
        public string UserName { get; set; }
        
        [DataType(DataType.DateTime)]
        public DateTime StartTime { get; set; }

        public string StartCity { get; set; } //Beijing 

        public string TripDays { get; set; } //i > j > k
       
        public string TripCities { get; set; } //  Calgary > Banff

        public string ImageUrl { get; set; }
       
    }
}

RC/SmartTrip/src/SmartTrip/Models/TripViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using Microsoft.AspNet.Mvc.Rendering;

namespace SmartTrip.Models
{
    public class TripViewModel
    {

        public TripViewModel()
        {

            Trip = new Trip();

            Countries = new List<Country>();

            Cities = new List<City>();

            CheckedCities = new List<CheckedCity>();

            Sceneries = new List<Scenery>();

            CheckedSceneries = new List<CheckedScenery>();
        }

        public Trip Trip { set; get; }

        public List<Country> Countries { set; get; }

        public List<City> Cities { set; get; }
        
        public List<CheckedCity> CheckedCities { set; get; }

        public List<Scenery> Sceneries { set; get; }

        public List<CheckedScenery> CheckedSceneries { set; get; }


    }


    public class CheckedCity 
    {
        public int CityId { set; get; }

        public bool Checked { set; get; }
    }

    public class CheckedScenery
    {
        public int SceneryId { set; get; }
        public bool Checked { set; get; }
    }
    

}

RC/SmartTrip/src/SmartTrip/Controllers/TripController.cs
using System;
using System.Net;
using Microsoft.AspNet.Mvc;
using SmartTrip.Models;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Hosting;
using System.IO;
using Microsoft.AspNet.Http;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.AspNet.Session;

using System.Globalization;
using Microsoft.AspNet.Builder;
using System.Text;
using System.Runtime.Serialization.Json;
using System.Collections;
using MaxMind.GeoIP2;
using System.Security.Claims;

namespace SmartTrip.Controllers
{
    public class TripController : Controller
    {
        private readonly ApplicationDbContext db;

        private IHostingEnvironment env;

        

        public TripController( ApplicationDbContext context,IHostingEnvironment hostingEnv )
        {
            db = context;
            env = hostingEnv;
       
        }

        public IActionResult TripStartTime()
        { 
            return View();
        }

        [HttpPost]
        public ActionResult TripStartTime(TripViewModel model, string btnPrevious, string btnNext)
        {
            
             if (btnNext != null)
            {
                if (ModelState.IsValid)
                {
                
                       
                 Context.Session.SetString("tripStartTime", model.Trip.StartTime.Ticks.ToString());
                   
                 return RedirectToAction("TripCountry");


                }
            }
            return View();
        }

        public IActionResult TripCountry()
        {
 
              var tripViewModel = new TripViewModel();

             // tripViewModel.Trip.StartTime = new DateTime( System.Convert.ToInt64( Context.Session.GetString("tripStartTime")) ) ;
              tripViewModel.Countries = db.Countries.ToList();

             return View(tripViewModel);
        }

        
        public IActionResult TripCity(int  id)
        {
            if (ModelState.IsValid)
            {

                var tripViewModel = new TripViewModel();

                tripViewModel.Cities = db.Cities.Where(c => c.CountryId == id).ToList();
                for (int i = 0; i < tripViewModel.Cities.Count; i++)
                {

                    CheckedCity city = new CheckedCity();
                    city.CityId = tripViewModel.Cities[i].Id;
                    city.Checked = false;

                    tripViewModel.CheckedCities.Add(city);
                }

                Context.Session.SetInt("countryId", id);
               

                return View(tripViewModel);
            }

            return View();
        }


        [HttpPost]
        public  IActionResult TripCity(TripViewModel model, string btnPrevious, string btnNext)
        {


            //List<City> cities = new List<City>();


            List<byte> arr = new List<byte>();

            foreach (var m in model.CheckedCities)
            { 
               if(m.Checked)
                {

                   arr.Add((byte)m.CityId);     
                // var city = await   db.Cities.FirstOrDefaultAsync(x => x.Id == m.CityId);
                //    cities.Add(city); 
                  
                }

            }

            Context.Session.Set("cities", arr.ToArray());

           // TempData["cities"] = cities;

            
            return RedirectToAction("TripOrderDays");
        }



    public IActionResult TripOrderDays()
        {
            TripViewModel tripViewModel = new TripViewModel();

            // suck with TempData
            // TempData["cities"].ToString();

            // tripViewModel.Cities =new List<City>( Newtonsoft.Json.JsonConvert.DeserializeObject<List<City>>(TempData["cities"].ToString()) );

            List<byte> list =   Context.Session.Get("cities").ToList();

          

            for (int i = 0; i < list.Count; i++) {

                City city =  db.Cities.FirstOrDefault(x => x.Id == (int)list[i]);

                tripViewModel.Cities.Add(city);

            }
              

            return View(tripViewModel);
        }

        [HttpPost]
        public IActionResult TripOrderDays(TripViewModel model, string btnPrevious, string btnNext)
        {

            // Get start city
            var reader = new DatabaseReader(env.WebRootPath + "\\GeoLite2-City.mmdb");

            IHttpConnectionFeature connection = Context.GetFeature<IHttpConnectionFeature>();

            string ip = connection != null ? connection.RemoteIpAddress.ToString() : null;

            if (ip == "127.0.0.1")
                ip = "128.101.101.101";

            var startCity = reader.City(ip);

            //Get  user Id

            string userId ;
            
            if (Context.User.IsSignedIn())
            {
                userId = Context.User.GetUserId();
                Context.Response.Cookies.Append("identity", userId);
                Context.Session.SetString("identity", userId);
            }
            else
            {


                //userId = Context.Request.Cookies["identity"];
                userId = Context.Session.GetString("identity");
                if (userId == null)
                {
                    userId = Guid.NewGuid().ToString();
                    Context.Response.Cookies.Append("identity", userId);
                    Context.Session.SetString("identity", userId);
                }

            }




            Trip trip = new Trip();

            trip.StartCity = startCity.City.Name;
            trip.UserName = userId;
            trip.StartTime = new DateTime(System.Convert.ToInt64(Context.Session.GetString("tripStartTime")));

            int Days = 0;

            for (int i = 0; i < model.Cities.Count; i++) {

                trip.TripDays += model.Cities[i].Days + ">";
                trip.TripCities += model.Cities[i].CityName + ">";
                Days += model.Cities[i].Days;
               

            }

            trip.ImageUrl = model.Cities[0].ImageUrl;

            trip.TripName = trip.TripCities + Days + "Day";

            db.Trips.Add(trip);
            db.SaveChanges();

            //todo fix a bug
            Trip myTrip =  db.Trips.FirstOrDefault(x => x.TripName == trip.TripName);

            for (int i = 0; i < model.Cities.Count; i++)
            {
                for (int j = 0; j < model.Cities[i].Days; j++) {

                    Schedule schedule = new Schedule();
                    schedule.ScheduleName = "Day" + (i+j+1);
                    schedule.StrCities = model.Cities[i].CityName + ">";
                    schedule.StrSceneries = ">";
                    schedule.StrHotels = ">";
                    schedule.ScheduleDate = trip.StartTime.AddDays(i+j);
                    schedule.TripId = myTrip.Id;
                    schedule.CountryId = Context.Session.GetInt("countryId").Value;
                    schedule.UserName = userId;

                    db.Schedules.Add(schedule);
                    db.SaveChanges();


                }
            }


            return RedirectToAction("Index");
        }


        public IActionResult Index()
        {
              
            string userId;

            if (Context.User.IsSignedIn())
            {
                userId = Context.User.GetUserId();
                Context.Response.Cookies.Append("identity", userId);
                Context.Session.SetString("identity", userId);
            }
            else
            {


                //userId = Context.Request.Cookies["identity"];
                userId = Context.Session.GetString("identity");
                if (userId == null)
                {
                    userId = Guid.NewGuid().ToString();
                    Context.Response.Cookies.Append("identity", userId);
                    Context.Session.SetString("identity", userId);
                }

            }


            var trips = db.Trips.Where(x=>x.UserName == userId).ToList();

            return View(trips);
        }

        public IActionResult TripSchedule(int id)
        {
            var schedules = db.Schedules.Where(x => x.TripId == id).ToList() ;

            return View(schedules);
        }


        public IActionResult TripScheduleInfo(int id)
        {

            ScheduleViewModel scheduleViewModel = new ScheduleViewModel();

            Schedule  schedule = db.Schedules.FirstOrDefault(x => x.Id == id);

            scheduleViewModel.Schedule = schedule;

            List<string> listCities = schedule.StrCities.Split('>').ToList();
            List<string> listSceneries = schedule.StrSceneries.Split('>').ToList();

            for (int i = 0; i < listCities.Count; i++) {

                City city = db.Cities.FirstOrDefault(x => x.CityName == listCities[i]);
                if(city != null)
                scheduleViewModel.Cities.Add(city);

            }

            for (int j = 0; j < listSceneries.Count; j++) {
                Scenery scenery = db.Sceneries.FirstOrDefault(x => x.SceneryName == listSceneries[j]);
                if (scenery != null)
                    scheduleViewModel.Sceneries.Add(scenery);

            }


            Context.Session.SetInt("scheduleId", id);
           

            return View(scheduleViewModel);
        }


        public IActionResult TripScenery(int id) {

            List<Image> listImages = db.Images.Where(x => x.SceneryId == id).ToList();
            Scenery scenery = db.Sceneries.FirstOrDefault(x => x.Id == id);

            SceneryViewModel sceneryViewModel = new SceneryViewModel();

            sceneryViewModel.Images = listImages;
            sceneryViewModel.Scenery = scenery;
            
            return View(sceneryViewModel);
        }

        public IActionResult AddScenery(int id) {

            Schedule schedule = db.Schedules.FirstOrDefault(x => x.Id == id);
            List<string> listCities = schedule.StrCities.Split('>').ToList();

RC/SmartTrip/src/SmartTrip/Views/Trip/AddCity.cshtml
@model SmartTrip.Models.ScheduleViewModel
    
@{
    ViewBag.Title = "Schedule - Select Cities";
    
}
   



@using (Html.BeginForm("AddCity", "Trip",  FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken();


    <table id="ScheduleCity">

            @for (int i=0; i< Model.Cities.Count; i++)
            {
                <tr>
                    <td>

                        @Html.HiddenFor(x=>x.CheckedCities[i].CityId)
                        <img title=@Model.Cities[i].CityName src=@Url.Content("~/images/"+Model.Cities[i].ImageUrl) width="180"/>

                    </td>
                    
                    <td >
                        
                        <div class="checkbox checkbox-material-teal-500">
                             <label>
                        @Html.CheckBoxFor(x => x.CheckedCities[i].Checked, new { id = Model.Cities[i].Id })
                             </label>
                         </div>

                     </td>
                </tr>
            }



    </table>

        <input type="submit" name="btnNext" value="next" class="btn btn-material-teal-500" />
}




<script type="text/javascript">
		$(document).ready(function()
		{

		    $.material.init()
		    
		});
</script>

RC/SmartTrip/src/SmartTrip/Views/Trip/AddScenery.cshtml
@model SmartTrip.Models.ScheduleViewModel
    
@{
    ViewBag.Title = "Schedule - Select Sceneries";
    
}
   



@using (Html.BeginForm("AddScenery", "Trip",  FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken();


    <table id="ScheduleScenery">

            @for (int i=0; i< Model.Sceneries.Count; i++)
            {
                <tr>
                    <td>

                        @Html.HiddenFor(x=>x.CheckedSceneries[i].SceneryId)
                        <img title=@Model.Sceneries[i].SceneryName src=@Url.Content("~/images/"+Model.Sceneries[i].ImageUrl) width="180"/>

                    </td>
                    
                    <td >
                        
                        <div class="checkbox checkbox-material-teal-500">
                             <label>
                        @Html.CheckBoxFor(x => x.CheckedSceneries[i].Checked, new { id = Model.Sceneries[i].Id })
                             </label>
                         </div>

                     </td>
                </tr>
            }



    </table>

        <input type="submit" name="btnNext" value="next" class="btn btn-material-teal-500" />
}




<script type="text/javascript">
		$(document).ready(function()
		{

		    $.material.init()
		    
		});
</script>

RC/SmartTrip/src/SmartTrip/Views/Trip/Delete.cshtml
@model SmartTrip.Models.Trip

@{
    ViewBag.Title = "Delete a trip";
}

@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <div class="form-group">


            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">

                    <img alt="@Model.TripName" src="@Url.Content("~/images/"+Model.ImageUrl)" />
                    <div class="label label-default label-material-teal-500 "> @Model.TripName </div>

                </div>
                <input type="submit" value="Delete" class="btn btn-flat btn-raised btn-material-teal-500" />

            </div>

        </div>
    </fieldset>
}

RC/SmartTrip/src/SmartTrip/Views/Trip/Edit.cshtml
@model SmartTrip.Models.Trip

@{
    ViewBag.Title = "Edit a Trip";
}

@using (Html.BeginForm("Edit","Trip",FormMethod.Post))
{
   @Html.AntiForgeryToken();

    <div class="form-group">
        @Html.LabelFor(x => x.TripName)
        @Html.EditorFor(x => x.TripName)
    </div>

     

        <input type="submit" value="submit" class="btn btn-default" />
}

RC/SmartTrip/src/SmartTrip/Views/Trip/Index.cshtml
@{
    ViewBag.Title = "Trip Index";
}


@if (Model.Count == 0)
{

    <h4>No Trip Items</h4>
    <a href="/Trip/TripStartTime/" class=" btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-add"> </a>


}
else
{

    <div class="row">
        @foreach (var trip in Model)
                {

            <div class="col-sm-5 col-md-5">
                <div class="thumbnail">
                    
                    <img alt="@trip.TripName" src="@Url.Content("~/images/"+trip.ImageUrl)" />

                    <div class="label label-info floating-label label-material-teal-500 "> @trip.TripName</div>

                    <a href="/Trip/TripSchedule/@trip.Id" class="btn btn-xs btn-sm btn-material-teal-500 btn-fab btn-flat btn-raised mdi-image-image "></a>
                    <a href="/Trip/Delete/@trip.Id" class="btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-clear "></a>
                    <a href="/Trip/TripStartTime/" class=" btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-add"> </a>

                </div>
            </div>

        }
    </div>
}

RC/SmartTrip/src/SmartTrip/Views/Trip/TripCity.cshtml
@model SmartTrip.Models.TripViewModel
    
@{
    ViewBag.Title = "Trip - Select Cities";
    
}
   

@using (Html.BeginForm("TripCity", "Trip",  FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken();


    <div class="row" id="TripCity">

            @for (int i = 0; i < Model.Cities.Count; i++)
            {

                <div class="col-sm-3 col-md-3">
                    @Html.HiddenFor(x => x.CheckedCities[i].CityId)
                    <img title=@Model.Cities[i].CityName src=@Url.Content("~/images/"+Model.Cities[i].ImageUrl) width="260" />



                    <div class="checkbox checkbox-material-teal-500">
                        <label>
                            @Html.CheckBoxFor(x => x.CheckedCities[i].Checked, new { id = Model.Cities[i].Id })
                        </label>
                    </div>
                </div>

            }



    </div>

        <input type="submit" name="btnNext" value="next" class="btn btn-material-teal-500" />
}




<script type="text/javascript">
		$(document).ready(function()
		{

		    $.material.init()
		    
		});
</script>

RC/SmartTrip/src/SmartTrip/Views/Trip/TripCountry.cshtml
@model SmartTrip.Models.TripViewModel
@{
    ViewBag.Title = "Trip Country";
}


<div class="row">
    
        @if (Model.Countries.Count == 0)
        {
            <h4>No Country Items</h4>
        }
        else
        {
            
                @foreach (var country in Model.Countries)
                {
                    <div class=" col-md-4 ">
                        <div >
                            <a  href='@Url.Action("TripCity","Trip",new {id = country.Id })'>
                            
                             <img width="260" title="@country.CountryName" src="@Url.Content("~/images/"+country.ImageUrl)">
                            </a>

                        </div>
                    </div>

                }

        }

                   

</div>

RC/SmartTrip/src/SmartTrip/Views/Trip/TripOrderDays.cshtml
@model SmartTrip.Models.TripViewModel
    
@{
    ViewBag.Title = "Set Order and Days";
    
}
   
@using (Html.BeginForm("TripOrderDays","Trip",  FormMethod.Post,new {@class="form-horizontal"}))
{
        @Html.AntiForgeryToken();

    
        <ol id="TripList" class="list-group" >

            @for (int i=0; i <  Model.Cities.Count; i++)
            {
              <li  class="list-group-item" >

                 
                  @Html.DisplayFor(m => m.Cities[i].CityName)
                 

                      @Html.LabelFor(m => m.Cities[i].Days)

                      @Html.TextBoxFor(m => m.Cities[i].Days, new { @id = Model.Cities[i].Id, @type = "number" })


                      @Html.HiddenFor(m => m.Cities[i].CityName, Model.Cities[i].CityName)

                      @Html.HiddenFor(m => m.Cities[i].CountryId,Model.Cities[i].CountryId)

                      @Html.HiddenFor(m => m.Cities[i].ImageUrl, Model.Cities[i].ImageUrl)
                    
                      <div  class="slider shor@(Model.Cities[i].Id)  slider-material-teal-500"></div>
                 

               </li>
            
            }

        </ol>

        <input type="submit" value="submit" class="btn btn-material-teal-500" />

}
  
  <script type="text/javascript">

      $(function () {
          $.material.init();

          @for (int i = 0; i < Model.Cities.Count; i++)
         {

         <text>
               

          $('.shor@(Model.Cities[i].Id)').noUiSlider({
                        start: 1,
                        step:1,
                        range: {
                            min: 0,
                           
                            max: 365
                        },
                        format: wNumb({
                            decimals:0
                        })
                    });

          $('.shor@(Model.Cities[i].Id)').Link('lower').to($('#@(Model.Cities[i].Id)'));


         </text>
          }


          Sortable.create(TripList, {});
          
            });

  </script>

RC/SmartTrip/src/SmartTrip/Views/Trip/TripScenery.cshtml
@{
    ViewBag.Title = "Trip Scenery";
}

<div id="myCarousel" class=" carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">

        <div class="item active ">

            <img src="@Url.Content("~/images/"+Model.Images[0].ImageUrl)" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <p>

                        @Model.Scenery.SceneryName

                    </p>
                </div>
            </div>
        </div>



        @for (int i = 1; i < Model.Images.Count; i++)
        {
            
             <div class="item  ">
        
                <img src="@Url.Content("~/images/"+Model.Images[i].ImageUrl)" class="img-responsive">
                <div class="container">
                    <div class="carousel-caption">
                        <p>

                                @Model.Scenery.SceneryName

                        </p>
                    </div>
                </div>
            </div>

        }
    </div>
</div>


<div class="list-group">

    <div class="list-group-item">
      <div class="row-action-primary">
      </div>
      <div class="row-content">
         
         <strong>概要:</strong> @Model.Scenery.Summary  <br/>
         <strong>门票:</strong> @Model.Scenery.Ticket   <br/>
         <strong>星级：</strong>@Model.Scenery.Star     <br /> 
         <strong>评分：</strong>@Model.Scenery.Score    <br />
         <strong>开放时间：</strong>@Model.Scenery.OpenTime <br />
         <strong>交通：</strong>@Model.Scenery.Traffic    <br />
         <strong>网址：</strong>@Model.Scenery.WebUrl     <br />
         <strong>电话:</strong> @Model.Scenery.Telephone   <br />
         
        

           
                  
      </div>

    </div>
    <div class="list-group-separator"></div>


</div>

RC/SmartTrip/src/SmartTrip/Views/Trip/TripSchedule.cshtml
@{
    ViewBag.Title = "Trip Schedule";
}


        @if (Model.Count == 0)
        {
            <h4>No Schedule Items</h4>
        }
        else
        {
            <div class="row">
                <div class="col-lg-4">
                    <div class="list-group">
                        @foreach (var schedule in Model)
                {

                           
                                <div class="list-group-item">
                                    <a  href="/Trip/TripScheduleInfo/@schedule.Id">
                                        <div class="row-picture">
                                            <h3 >   @schedule.ScheduleName </h3>
                                        </div>

                                        <div class="row-content ">
                                            <h4 >@schedule.StrCities</h4>
                                            <h4>@schedule.StrSceneries</h4>
                                        </div>
                                    </a>
                                 </div>
                                
                            
                            <div class="list-group-separator"></div>
                        }

                    </div>
                </div>
            </div>
        }
        
   

RC/SmartTrip/src/SmartTrip/Views/Trip/TripScheduleInfo.cshtml
@model SmartTrip.Models.ScheduleViewModel 
@using Microsoft.AspNet.Http

@{
    ViewBag.Title = "Trip Schedule Detail";
}


@using System.Security.Claims

@{
    string userId = User.GetUserId();
    if (userId == null) {
        userId = Context.Session.GetString("identity");
    }
}



@* Markup removed for brevity *@

    
        @if (Model.Sceneries.Count == 0)
        {
            <h4>No Schedule Detail</h4>
        }
        else
        {
               

                <div class="row">
                    <div class="col-sm-4">
                        <div class="list-group">
                            @foreach (var scenery in Model.Sceneries)
                            {
                                <div class="list-group-item">
                                    <div class="row-picture circle">

                                        <img src="@Url.Content("~/images/"+scenery.ImageUrl)">
                                    </div>

                                    <div class="row-content">
                                        <a href="/Trip/TripScenery/@scenery.Id">@scenery.SceneryName</a>


                                    </div>
                                </div>
                                <div class="list-group-separator"></div>

                            }
                        </div>
                        </div>
                    </div>

        }



          @if(userId == Model.Schedule.UserName)
                { 
                    <div class="btn btn-flat btn-material-teal-400 "> @Html.ActionLink("City", "AddCity", "Trip", new { id = Model.Schedule.Id })</div>
                    <div class="btn btn-flat btn-material-teal-400 "> @Html.ActionLink("Scenery", "AddScenery", "Trip", new { id = Model.Schedule.Id })</div>
                }   

RC/SmartTrip/src/SmartTrip/Views/Trip/TripStartTime.cshtml
@model SmartTrip.Models.TripViewModel
    
@{
    ViewBag.Title = "Trip - Select  StartTime";
    
}


   
@using (Html.BeginForm("TripStartTime", "Trip",  FormMethod.Post,new{ @class="form-horizontal"}))
{

   
        @Html.AntiForgeryToken();
   

         <div class="form-group input-group-sm">

            
            @Html.TextBoxFor(x => x.Trip.StartTime, new{ placeholder="Select start date", @class="form-control foating-label", @id = "startDate", @type = "text" })
       </div>

<div class="form-group">

    <input type="submit" name="btnNext" value="next" class="btn btn-material-teal-500" />
</div>
}



<script type="text/javascript">
		$(document).ready(function()
		{
			$('#startDate').bootstrapMaterialDatePicker
			({
			    date: "true",
                format:"YYYY-MM-DD",
				time: false
			});
			
		
			
		});
</script>