RC/SmartTrip/src/SmartTrip/Models/Country.cs
using System.Collections.Generic;

namespace SmartTrip.Models
{
    public class Country
    {
        public int Id { set; get; }
        public string CountryName { set; get; }

        public string ImageUrl { set; get; }

       
    }
}

RC/SmartTrip/src/SmartTrip/Models/CountryViewModel.cs
using System.Collections.Generic;

namespace SmartTrip.Models
{
    public class CountryViewModel
    {
        public Country Country { get; set; }
        
    }
}

RC/SmartTrip/src/SmartTrip/Controllers/CountryController.cs
using System;
using System.Net;
using Microsoft.AspNet.Mvc;
using SmartTrip.Models;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.AspNet.Http;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNet.Hosting;
using System.IO;

namespace SmartTrip.Controllers
{
    public class CountryController : Controller
    {
        private readonly ApplicationDbContext db;

        private IHostingEnvironment env;

        public CountryController(ApplicationDbContext context,IHostingEnvironment hostingEnv)
        {
            db = context;
            env = hostingEnv;
        }

        public async Task<string> SaveFile(IFormFile file)
        {
            var parsedContentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);

            string fileName = parsedContentDisposition.FileName.Trim('"');

            string filePath = Path.Combine(env.WebRootPath + "\\images\\" + fileName);

            await file.SaveAsAsync(filePath);

            //return filePath;
            return fileName;
        }



        public IActionResult Index()
        {
            var countries = db.Countries.ToList();

            return View(countries);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CountryViewModel model,IFormFile file)
        {
            //IFormFile
            var filePath = "";
            if (file != null)
                filePath = await SaveFile(file);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var country = new Country
            {
                CountryName = model.Country.CountryName,
                ImageUrl = (filePath.Length > 0) ? filePath : " "

            };

            db.Countries.Add(country);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
           }

        public async Task<IActionResult> Edit(int id)
        {
            var country = await db.Countries.SingleOrDefaultAsync(x => x.Id == id);
            if (country == null)
            {
                return HttpNotFound();
            }

            return View(country);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Country model,IFormFile file)
        {
            //IFormFile
            var filePath = "";
            if (file != null)
                filePath = await SaveFile(file);


            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var country = await db.Countries.SingleOrDefaultAsync(x => x.Id == id);
            if (country == null)
            {
                return HttpNotFound();
            }

            country.CountryName = model.CountryName;

            country.ImageUrl = (filePath.Length > 0) ? filePath : model.ImageUrl;

            // TODO Exception handling
            db.SaveChanges();

            return RedirectToAction("Index", new { id = id });
        }

        // GET: Countries/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            Country country = await db.Countries.SingleOrDefaultAsync(x => x.Id == id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Country country = await db.Countries.SingleOrDefaultAsync(x => x.Id == id);
            db.Countries.Remove(country);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
           
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

RC/SmartTrip/src/SmartTrip/Views/Country/Create.cshtml
@model SmartTrip.Models.CountryViewModel
    
@{
    ViewBag.Title = "Create a Country";
}




        @using (Html.BeginForm("Create", "Country", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken();


            <fieldset>
                
    <legend></legend>
    <div class="form-group">

        @Html.TextBoxFor(x => x.Country.CountryName, new { @class = "form-control", placeholder = "Country Name" })
    </div>


    <div class="form-group">
        <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
        <input type="file" name="file" id="file1" />
    </div>


    <div class="form-group">
        <input type="submit" value="Create" class="btn  btn-flat btn-raised btn-material-teal-500" />
    </div>



</fieldset>

        }

RC/SmartTrip/src/SmartTrip/Views/Country/Delete.cshtml
@model SmartTrip.Models.Country

@{
    ViewBag.Title = "Delete a country";
}


   
    @using (Html.BeginForm( new {@class="form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        <fieldset>
            <div class="form-group">


                <div class="col-sm-4 col-md-4">
                    <div class="thumbnail">

                        <img alt="@Model.CountryName" src="@Url.Content("~/images/"+Model.ImageUrl)" />
                        <div class="label label-default label-material-teal-500 "> @Model.CountryName </div>
                       
                    </div>
                    <input type="submit" value="Delete" class="btn btn-flat btn-raised btn-material-teal-500" />

                </div>

            </div>
        </fieldset>
    }
    

RC/SmartTrip/src/SmartTrip/Views/Country/Edit.cshtml
@model SmartTrip.Models.Country

@{
    ViewBag.Title = "Edit a Country";
}


<div class="row">
    <div class="col-sm-4 col-md-4">
        <div class="thumbnail">

            <img alt="@Model.CountryName" src="@Url.Content("~/images/"+Model.ImageUrl)" />
            <div class="label label-default label-material-teal-500 "> @Model.CountryName </div>

        </div>

    </div>
</div>

@using (Html.BeginForm("Edit", "Country", FormMethod.Post, new {@class="form-horizotal", enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken();

  
<div class="form-group">


    @Html.TextBoxFor(x => x.CountryName, new { @class = "form-control" })
</div>

<div class="form-group">
    <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
    <input type="file" name="file" id="file1" />
</div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-flat btn-raised btn-material-teal-500" />
    </div>
}

RC/SmartTrip/src/SmartTrip/Views/Country/Index.cshtml
@{
    ViewBag.Title = "Country Index";
}


@* Markup removed for brevity *@


        @if (Model.Count == 0)
        {
                    
            <h4>No Country Items</h4>
            <a href="/Country/Create/" class=" btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-add"> </a>

        }
        else
        {

            <div class="row">
                @foreach (var country in Model)
                {

                <div class="col-sm-4 col-md-4">
                     <div class="thumbnail">
                    
                        <img alt="@country.CountryName"  src="@Url.Content("~/images/"+country.ImageUrl)" />
                        <div class="label label-default label-material-teal-500 "> @country.CountryName</div>
                    
                         <a href="/Country/Edit/@country.Id" class="btn btn-xs btn-sm btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-create "></a>
                         <a href="/Country/Delete/@country.Id" class="btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-clear "></a>
                        
                    </div>
               </div>
                           
               }
           </div>
        }


           

 