RC/SmartTrip/src/SmartTrip/Models/Scenery.cs
using System;
using System.Collections.Generic;

namespace SmartTrip.Models
{

    public  class   Category {

     public List<string> CategoryType { set; get; }

     public Category() {

            CategoryType = new List<string>();
            CategoryType.Add("scenery");
            CategoryType.Add("activity");
            CategoryType.Add("cate");
            CategoryType.Add("shopping");
            CategoryType.Add("traffic");
        }

    }
   
    public class Scenery
    {
       
        public int Id { set; get; }

        public string SceneryName { set; get; }
        
        //assessment
        public int Star { set; get; }

        // 
        public int Score { set; get; }

        public int Visited { set; get; }

        public int Ranking { set; get; }
        //

        public string Summary { set; get; }

        //basic info
        public string Ticket { set; get; }

        public string OpenTime { set; get; }

        public string Traffic { set; get; }

        public string WebUrl { set; get; }

        public string Category { set; get; }

        public string Telephone { set; get; }

        public Decimal Price { set; get; }
        public string Currency { set; get; }

        public string ImageUrl { set; get; }
        
        //many to one
        public int CityId { set; get; }

        public int ScheduleId  { set; get; }


        //one to many
        public virtual ICollection<Image> Images { set; get; }
        public virtual ICollection<SceneryComment> SceneryComments { set; get; }

        
	
    }
}

RC/SmartTrip/src/SmartTrip/Models/SceneryViewModel.cs
using Microsoft.AspNet.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace SmartTrip.Models
    
{

    public class SceneryViewModel
    {
        
        public List<Image> Images { set; get; }
        public Scenery Scenery { set; get; }

        public IEnumerable<SelectListItem> Cities { set; get; }

        public IEnumerable<SelectListItem> Categories { set; get; }

        public IEnumerable<SelectListItem> Currencies { set; get; }
       
    }
}

RC/SmartTrip/src/SmartTrip/Controllers/SceneryController.cs
using System;
using System.Net;
using Microsoft.AspNet.Mvc;
using SmartTrip.Models;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Hosting;
using System.IO;
using Microsoft.AspNet.Http;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNet.Mvc.Rendering;

using System.Globalization;

namespace SmartTrip.Controllers
{
    public class SceneryController : Controller
    {
        private readonly ApplicationDbContext db;

        private IHostingEnvironment env;

       public IEnumerable<SelectListItem> InitCity()
        {

            return  new SelectList(db.Cities.ToList(),"Id","CityName");

        }

        public  IEnumerable<SelectListItem> InitCategory()
        {
            var category = new Category();

            return new SelectList( category.CategoryType.AsEnumerable());
         
        }

        public  IEnumerable<SelectListItem> InitCurrency()
        {
            // CurrentCulture.NumberFormat.CurrencySymbol

            List<string> currencies = new List<string>();

                 
            foreach (var cultureInfo in CultureInfo.GetCultures(CultureTypes.SpecificCultures))

            {
                RegionInfo ri;

                try {

                    ri = new RegionInfo(cultureInfo.LCID);
                }
                catch
                {

                    ri = null;
                }

                if(ri != null)
                currencies.Add(ri.ISOCurrencySymbol);
            }
            
           return new SelectList(currencies.AsEnumerable());    
        }

        private async Task<List<string>> SaveFiles(IEnumerable<IFormFile> files)
        {

            List<string> imageUrlList = new List<string>();

            foreach (var file in files)
            {

                var parsedContentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);

                string fileName = parsedContentDisposition.FileName.Trim('"');

                string filePath = Path.Combine(env.WebRootPath + "\\images\\" + fileName);

                await file.SaveAsAsync(filePath);

                //  imageUrlList.Add(filePath);
                imageUrlList.Add(fileName);
            }

            return imageUrlList;
        }


        private async Task<List<Image>> SaveFiles1(IEnumerable<IFormFile> files)
        {

            List<Image> imageList = new List<Image>();

            foreach (var file in files)
            {

                var parsedContentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);

                string fileName = parsedContentDisposition.FileName.Trim('"');

                string filePath = Path.Combine(env.WebRootPath + "\\images\\" + fileName);

                await file.SaveAsAsync(filePath);

                var image = new Image
                {

                  //  ImageUrl = filePath,
                  ImageUrl = fileName,

                };

                imageList.Add(image);
            }

            return imageList;
        }


        public SceneryController(ApplicationDbContext context,IHostingEnvironment hostingEnv )
        {
            db = context;
            env = hostingEnv;
        }

        public IActionResult Index()
        {
            var sceneries = db.Sceneries.ToList();

            return View(sceneries);
        }
   
        public IActionResult Create()
        {
           var sceneryViewModel = new SceneryViewModel();
          
           sceneryViewModel.Cities =  InitCity();
           sceneryViewModel.Categories = InitCategory();
           sceneryViewModel.Currencies = InitCurrency();

            return View(sceneryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IEnumerable<IFormFile> files,SceneryViewModel model)
        {
            //IFormFile
            List<Image> imageList = new List<Image>();

            if (files != null)
              imageList = await SaveFiles1(files);


            //SceneryEditModel
            //   if (!ModelState.IsValid)
            //   {
            //       return View(model);
            //   }

            var scenery = new Scenery
            {

                SceneryName = model.Scenery.SceneryName,
                Star = model.Scenery.Star,
                Summary = model.Scenery.Summary,
                Ticket = model.Scenery.Ticket,
                OpenTime = model.Scenery.OpenTime,
                Traffic = model.Scenery.Traffic,
                WebUrl = model.Scenery.WebUrl,
                Category = model.Scenery.Category,   //
                Telephone = model.Scenery.Telephone,
                Price = model.Scenery.Price,
                Currency = model.Scenery.Currency,  //
                CityId = model.Scenery.CityId,    //
                Images = imageList,
                ImageUrl = imageList[0].ImageUrl
            };

            db.Sceneries.Add(scenery);

            if(imageList.Count() > 0)
            {
                foreach (var image in imageList)
                {
                    image.SceneryId = scenery.Id;
                    db.Images.Add(image);
                }
            }

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
           }

        public async Task<IActionResult> Edit(int id)
        {
            //
            var sceneryViewModel = new SceneryViewModel();
            sceneryViewModel.Cities = InitCity();
            sceneryViewModel.Categories = InitCategory();
            sceneryViewModel.Currencies = InitCurrency();
            
            //Edit
            var scenery = await db.Sceneries.SingleOrDefaultAsync(x => x.Id == id);
            if (scenery == null)
            {
                return HttpNotFound();
            }

            sceneryViewModel.Scenery = scenery;

            return View(sceneryViewModel);
        }

        

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SceneryViewModel model,IEnumerable<IFormFile> files)
        {

            //IFormFile
            List<Image> imageList = new List<Image>();
                
             if(files != null)   
               imageList =  await SaveFiles1(files);

            //SceneryEditModel
            
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            

            var scenery = await db.Sceneries.SingleOrDefaultAsync(x => x.Id == id);
            if (scenery == null)
            {
                return HttpNotFound();
            }

            scenery.SceneryName = model.Scenery.SceneryName;
           
            scenery.Star = model.Scenery.Star;
            scenery.Summary =  model.Scenery.Summary;
            scenery.Ticket = model.Scenery.Ticket;
            scenery.OpenTime = model.Scenery.OpenTime;
            scenery.Traffic = model.Scenery.Traffic;
            scenery.WebUrl = model.Scenery.WebUrl;
            scenery.Category = model.Scenery.Category;
            scenery.Telephone = model.Scenery.Telephone;
            scenery.Price = model.Scenery.Price;
            scenery.Currency = model.Scenery.Currency;
            scenery.CityId = model.Scenery.CityId;
            scenery.Images = imageList;


            // TODO Exception handling
            if (imageList.Count() > 0)
            {
                foreach (var image in imageList)
                {
                    image.SceneryId = scenery.Id;
                    db.Images.Add(image);
                }
            }



            db.SaveChanges();


            return RedirectToAction("Index", new { id = id });
        }

        // GET: Sceneries/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            Scenery scenery = await db.Sceneries.SingleOrDefaultAsync(x => x.Id == id);
            if (scenery == null)
            {
                return HttpNotFound();
            }
            return View(scenery);
        }

        // POST: Sceneries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Scenery scenery = await db.Sceneries.SingleOrDefaultAsync(x => x.Id == id);
            db.Sceneries.Remove(scenery);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
           
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

RC/SmartTrip/src/SmartTrip/Views/Scenery/Create.cshtml
@model SmartTrip.Models.SceneryViewModel
    
@{
    ViewBag.Title = "Create a Scenery";
    
}
   

@using (Html.BeginForm("Create","Scenery",  FormMethod.Post, new { enctype = "multipart/form-data",@class="form-horizontal" }))
{
        @Html.AntiForgeryToken();

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.SceneryName,new{ @class="form-control" ,placeholder="Scenery Name"})
        </div>

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.Star, new { @class = "form-control", placeholder = "Star" })
        </div>

        
        <div class="form-group">
            
            @Html.TextBoxFor(x => x.Scenery.Summary, new { @class = "form-control", placeholder = "Summary" })
        </div>

        <div class="form-group">
            
            @Html.TextBoxFor(x => x.Scenery.Ticket, new { @class = "form-control", placeholder = "Ticket" })
        </div>

        <div class="form-group">
            
            @Html.TextBoxFor(x => x.Scenery.OpenTime, new { @class = "form-control", placeholder = "Open Time" })
        </div>

        <div class="form-group">
            
            @Html.TextBoxFor(x => x.Scenery.Traffic, new { @class = "form-control", placeholder = "Traffic" })
        </div>

        <div class="form-group">
            
            @Html.TextBoxFor(x => x.Scenery.WebUrl, new { @class = "form-control", placeholder = "Website" })
        </div>

        <div class="form-group">
           
            @Html.DropDownListFor(x => x.Scenery.Category,Model.Categories, new { @class = "form-control"})
        </div>

        <div class="form-group">
            
            @Html.TextBoxFor(x => x.Scenery.Telephone, new { @class = "form-control", placeholder = "Telephone" })
        </div>

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.Price, new { @class = "form-control", placeholder = "Price" })
        </div>

        <div class="form-group">
            
            @Html.DropDownListFor(x => x.Scenery.Currency,Model.Currencies, new { @class = "form-control" })
        </div>

       
        <div class="form-group">
            
            @Html.DropDownListFor(x => x.Scenery.CityId,Model.Cities, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
            <input type="file" name="files" id="file1" />
            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
            <input type="file" name="files" id="file2" />
            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
              <input type="file" name="files" id="file3" />
        </div>

        
        <input type="submit" value="Create" class="btn btn-flat btn-raised btn-material-teal-500" />
}

RC/SmartTrip/src/SmartTrip/Views/Scenery/Delete.cshtml
@model SmartTrip.Models.Scenery

@{
    ViewBag.Title = "Delete a scenery";
}

@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <div class="form-group">


            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">

                    <img alt="@Model.SceneryName" src="@Url.Content("~/images/"+Model.ImageUrl)" />
                    <div class="label label-default label-material-teal-500 "> @Model.SceneryName </div>

                </div>
                <input type="submit" value="Delete" class="btn btn-flat btn-raised btn-material-teal-500" />

            </div>

        </div>
    </fieldset>
}

RC/SmartTrip/src/SmartTrip/Views/Scenery/Edit.cshtml
@model SmartTrip.Models.SceneryViewModel

@{
    ViewBag.Title = "Edit a Scenery";
}

@using (Html.BeginForm("Edit","Scenery",FormMethod.Post, new { @class="form-horizontal",enctype = "multipart/form-data" }))
{
   @Html.AntiForgeryToken();

    <div class="form-group">
       
        @Html.TextBoxFor(x => x.Scenery.SceneryName,new { @class="form-control"})
    </div>

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.Star, new { @class = "form-control" })
        </div>


        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.Summary, new { @class = "form-control" })
        </div>

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.Ticket, new { @class = "form-control" })
        </div>

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.OpenTime, new { @class = "form-control" })
        </div>

        <div class="form-group">
            
            @Html.TextBoxFor(x => x.Scenery.Traffic, new { @class = "form-control" })
        </div>

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.Scenery.WebUrl, new { @class = "form-control" })
        </div>

        <div class="form-group">
           
            @Html.DropDownListFor(x => x.Scenery.Category, Model.Categories, new { @class = "form-control" })
        </div>

        <div class="form-group">
          
            @Html.TextBoxFor(x => x.Scenery.Telephone, new { @class = "form-control" })
        </div>

        <div class="form-group">
          
            @Html.TextBoxFor(x => x.Scenery.Price,new { @class = "form-control" })
        </div>

        <div class="form-group">
           
            @Html.DropDownListFor(x => x.Scenery.Currency, Model.Currencies, new { @class = "form-control" })
        </div>


        <div class="form-group">
          
            @Html.DropDownListFor(x => x.Scenery.CityId, Model.Cities, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
            <input type="file" name="files" id="file1" />

            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
            <input type="file" name="files" id="file2" />

            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
            <input type="file" name="files" id="file3" />
        </div>


        <input type="submit" value="Save" class="btn btn-flat btn-raised btn-material-teal-500" />
}

RC/SmartTrip/src/SmartTrip/Views/Scenery/Index.cshtml
@{
    ViewBag.Title = "Scenery Index";
}

@if (Model.Count == 0)
{

    <h4>No Scenery Items</h4>
    <a href="/Scenery/Create/" class=" btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-add"> </a>

}
else
{

    <div class="row">
        @foreach (var scenery in Model)
                {

            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">

                    <img alt="@scenery.SceneryName" src="@Url.Content("~/images/"+scenery.ImageUrl)" />
                    <div class="label label-default label-material-teal-500 "> @scenery.SceneryName</div>

                    <a href="/Scenery/Edit/@scenery.Id" class="btn btn-xs btn-sm btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-create "></a>
                    <a href="/Scenery/Delete/@scenery.Id" class="btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-clear "></a>
                    <a href="/Scenery/Create/" class=" btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-add"> </a>

                </div>
            </div>

        }
    </div>
}