RC/SmartTrip/src/SmartTrip/Models/City.cs
using System.Collections.Generic;

namespace SmartTrip.Models
{
    public class City
    {
        public int Id { set; get; }

        public string CityName { set; get; }

        public string ImageUrl { set; get; }

		public string Summary { set; get; }

        public int Visited { set; get; }


        public int Days { set; get; }

        //many to one
        public int CountryId { set; get; }
       
    }
}

RC/SmartTrip/src/SmartTrip/Models/CityViewModel.cs
using Microsoft.AspNet.Mvc.Rendering;
using System.Collections.Generic;

namespace SmartTrip.Models
{
    public class CityViewModel
    {
        public City City { get; set; }  
        public IEnumerable<SelectListItem> Countries { get; set; }

    }
}

RC/SmartTrip/src/SmartTrip/Controllers/CityController.cs
using System;
using System.Net;
using Microsoft.AspNet.Mvc;
using SmartTrip.Models;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Hosting;
using System.IO;
using Microsoft.AspNet.Http;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNet.Mvc.Rendering;

namespace SmartTrip.Controllers
{
    public class CityController : Controller
    {
        private readonly ApplicationDbContext db;

        private IHostingEnvironment env;

        public CityController(ApplicationDbContext context,IHostingEnvironment hostingEnv )
        {
            db = context;
            env = hostingEnv;
        }

        public IActionResult Index()
        {
            var cities = db.Cities.ToList();
           return View(cities);
        }
  
        public IActionResult Create()
        {
           
            var cityViewModel = new CityViewModel();
            cityViewModel.Countries = new SelectList(db.Countries.ToList(), "Id", "CountryName");
            return View(cityViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file,CityViewModel model)
        {

            //IFormFile
            var filePath = "";
            if (file != null)
                filePath = await SaveFile(file);


            //CityViewModel

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var city = new City
            {

                CityName = model.City.CityName,
                ImageUrl = (filePath.Length > 0) ? filePath : model.City.ImageUrl,
                Summary = model.City.Summary,
                CountryId = model.City.CountryId

            };

            db.Cities.Add(city);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
           }

        public async Task<IActionResult> Edit(int id)
        {

           
            var city = await db.Cities.SingleOrDefaultAsync(x => x.Id == id);
            if (city == null)
            {
                return HttpNotFound();
            }

            var cityViewModel = new CityViewModel {
                City = city
            };
            cityViewModel.Countries = new SelectList(db.Countries.ToList(), "Id", "CountryName");
            
            return View(cityViewModel);
        }


        public async Task<string> SaveFile(IFormFile file)
        {
            var parsedContentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);

            string fileName = parsedContentDisposition.FileName.Trim('"');

                                            
            string filePath = Path.Combine(env.WebRootPath + "\\images\\" + fileName);
            
            await file.SaveAsAsync(filePath);

            //return filePath;
            return fileName;
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, CityViewModel model,IFormFile file)
        {

            //IFormFile
            var filePath = "";
            if (file != null)
                filePath = await SaveFile(file);
           
            //CityViewModel
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var city = await db.Cities.SingleOrDefaultAsync(x => x.Id == id);
            if (city == null)
            {
                return HttpNotFound();
            }


            
            city.CityName = model.City.CityName;
            city.ImageUrl = (filePath.Count()>0)? filePath : model.City.ImageUrl;
            city.Summary = model.City.Summary;
            city.CountryId = model.City.CountryId;
            

            // TODO Exception handling
            db.SaveChanges();

            return RedirectToAction("Index", new { id = id });
        }

        // GET: Cities/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.SingleOrDefaultAsync(x => x.Id == id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            City city = await db.Cities.SingleOrDefaultAsync(x => x.Id == id);
            db.Cities.Remove(city);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
           
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

RC/SmartTrip/src/SmartTrip/Views/City/Create.cshtml
@model SmartTrip.Models.CityViewModel
    
@{
    ViewBag.Title = "Create a City";
    
}
   

@using (Html.BeginForm("Create","City",  FormMethod.Post, new { enctype = "multipart/form-data",@class="form-horizontal"}))
{
        @Html.AntiForgeryToken();

        <div class="form-group">
           
            @Html.TextBoxFor(x => x.City.CityName, new { @class = "form-control", placeholder = "City Name" })
        </div>

       
        <div class="form-group">
            
            @Html.TextBoxFor(x => x.City.Summary,new { @class = "form-control", placeholder = "City Summary" })
        </div>

        <div class="form-group">
         
            @Html.DropDownListFor(x => x.City.CountryId, Model.Countries, new { @class = "form-control", placeholder = "Select Country" })
        </div>

        <div class="form-group">
            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
            <input type="file" name="file" id="file1" />
        </div>

        
        <input type="submit" value="Create" class="btn btn-flat btn-raised btn-material-teal-500" />
}

RC/SmartTrip/src/SmartTrip/Views/City/Delete.cshtml
@model SmartTrip.Models.City

@{
    ViewBag.Title = "Delete a city";
}

@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <div class="form-group">


            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">

                    <img alt="@Model.CityName" src="@Url.Content("~/images/"+Model.ImageUrl)" />
                    <div class="label label-default label-material-teal-500 "> @Model.CityName </div>

                </div>
                <input type="submit" value="Delete" class="btn btn-flat btn-raised btn-material-teal-500" />

            </div>

        </div>
    </fieldset>
}

RC/SmartTrip/src/SmartTrip/Views/City/Edit.cshtml
@model SmartTrip.Models.CityViewModel

@{
    ViewBag.Title = "Edit a City";
}

<div class="row">
    <div class="col-sm-4 col-md-4">
        <div class="thumbnail">

            <img alt="@Model.City.CityName" src="@Url.Content("~/images/"+Model.City.ImageUrl)" />
            <div class="label label-default label-material-teal-500 "> @Model.City.CityName </div>

        </div>

    </div>
</div>


@using (Html.BeginForm("Edit","City",FormMethod.Post, new { @class = "form-horizotal", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();

    <div class="form-group">
        
        @Html.TextBoxFor(x => x.City.CityName, new { @class = "form-control" })
    </div>
 
    
        <div class="form-group">
           
            @Html.TextBoxFor(x => x.City.Summary, new { @class = "form-control" })
        </div>

        <div class="form-group">
           
            @Html.DropDownListFor(x => x.City.CountryId, Model.Countries, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <input type="text" readonly="" class="form-control floating-label" placeholder="Browse image..." />
            <input type="file" name="file" />
        </div>

    <input type="submit" value="Save" class="btn btn-flat btn-raised btn-material-teal-500" />
}

RC/SmartTrip/src/SmartTrip/Views/City/Index.cshtml
@{
    ViewBag.Title = "City Index";
}

@if (Model.Count == 0)
{

    <h4>No City Items</h4>
    <a href="/City/Create/" class=" btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-add"> </a>

}
else
{

    <div class="row">
        @foreach (var city in Model)
                {

            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">

                    <img alt="@city.CityName" src="@Url.Content("~/images/"+city.ImageUrl)"  width="300" height="200" />
                    <div class="label label-default label-material-teal-500 "> @city.CityName</div>

                    <a href="/City/Edit/@city.Id" class="btn btn-xs btn-sm btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-create "></a>
                    <a href="/City/Delete/@city.Id" class="btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-clear "></a>
                    <a href="/City/Create/" class=" btn btn-xs btn-material-teal-500 btn-fab btn-flat btn-raised mdi-content-add"> </a>

                </div>
            </div>

        }
    </div>
}